### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [azyobuzin/rust-oauthcli#8]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by azyobuzin** [comment]
Yes, I know. I'm planning to use another library. But it will take time while I'm busy.

**Comment by azyobuzin** [comment]
https://github.com/azyobuzin/rust-oauthcli/commit/c5a8327ce62b048bdc74fedc76efa3e95b684aa2
